const express = require('express');
const router = express.Router();
const { readDB, writeDB } = require('../db/database');
const aiDaemon = require('../services/ai_daemon');

/**
 * List MoMs
 */
router.get('/', (req, res) => {
  const db = readDB();
  const status = req.query.status;
  let list = db.moms;
  if (status) {
    list = list.filter(m => m.status === status);
  }
  res.json({ moms: list });
});

/**
 * Get single MoM
 */
router.get('/:id', (req, res) => {
  const db = readDB();
  const mom = db.moms.find(m => m.id === req.params.id || m.meeting_id === req.params.id);
  if (!mom) return res.status(404).json({ error: 'MoM not found' });
  res.json({ mom });
});

/**
 * Update MoM (save draft / edit)
 */
router.put('/:id', (req, res) => {
  const { title, agenda, discussion, decisions, action_items, status } = req.body;
  const db = readDB();
  const index = db.moms.findIndex(m => m.id === req.params.id || m.meeting_id === req.params.id);
  if (index === -1) return res.status(404).json({ error: 'MoM not found' });

  db.moms[index] = {
    ...db.moms[index],
    title: title || db.moms[index].title,
    agenda: agenda || db.moms[index].agenda,
    discussion: discussion || db.moms[index].discussion,
    decisions: decisions || db.moms[index].decisions,
    action_items: action_items || db.moms[index].action_items,
    status: status || db.moms[index].status,
    last_edited_at: new Date().toISOString()
  };

  writeDB(db);
  res.json({ message: "MoM saved successfully", mom: db.moms[index] });
});

/**
 * Approve & Sign-off MoM
 */
router.post('/:id/approve', (req, res) => {
  const db = readDB();
  const index = db.moms.findIndex(m => m.id === req.params.id || m.meeting_id === req.params.id);
  if (index === -1) return res.status(404).json({ error: 'MoM not found' });

  db.moms[index].status = 'approved';
  db.moms[index].signed_by_admin = true;
  db.moms[index].approved_at = new Date().toISOString();

  // Log AI action
  db.ai_logs.unshift({
    id: `log_${Date.now()}`,
    timestamp: new Date().toISOString(),
    task_name: "MoM Official Seal & Archive",
    meeting_id: db.moms[index].meeting_id,
    action_taken: `Official Minutes for '${db.moms[index].title}' approved and digitally signed. Dispatched archive copies.`,
    status: "success",
    latency_ms: 24
  });

  writeDB(db);
  res.json({ message: "MoM officially approved and signed", mom: db.moms[index] });
});

/**
 * Trigger AI generation from a meeting
 */
router.post('/generate', (req, res) => {
  const { meetingId } = req.body;
  const newMoM = aiDaemon.generateMoMForMeeting(meetingId);
  if (!newMoM) {
    return res.status(404).json({ error: 'Meeting not found' });
  }
  res.json({ message: "MoM generated by AI", mom: newMoM });
});

module.exports = router;
